import Head from 'next/head';
import { useRouter } from 'next/router';
import NavElement from './NavElement';

const PageHeader: React.FC = () => {
  const router = useRouter();

  // TODO better in external file
  const routes: { text: string; href: string }[] = [
    { text: 'About', href: '/' },
    { text: 'Work, etc.', href: '/work' },
    { text: 'Side', href: '/side' },
    { text: 'Life', href: '/life' },
  ];

  return (
    <>
      <Head>
        <title>philbellamy.net</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <div className='py-5'>
          <h1 className='text-5xl my-3'>Phil Bellamy.</h1>
          <h2 className='text-lg font-mono uppercase'>
            Full-Stack Web Developer
          </h2>
        </div>
        <nav className='mb-8'>
          <ul className='flex flex-wrap justify-between'>
            {routes.map((route) => {
              return (
                <NavElement
                  key={route.href}
                  text={route.text}
                  href={route.href}
                  active={router.route == route.href}
                />
              ); // this wouldn't work for sub-pages
            })}
          </ul>
        </nav>
      </header>
    </>
  );
};

export default PageHeader;
